### ISSUE TITLE
Movim doesn't work

### ISSUE THREAD

**Issue by pisua** [movim/movim_docker#16]
Hi, 
we try deploy without docker compose a full docker environment using these command for deploying our own movim pod for our company. 

-> create a  docker network 
docker network create  --subnet=172.20.0.0/16 my-net 

-> create postgres container 
docker create --restart=always --name postgres -p 5432:5432 \
-e POSTGRES_USER=root -e POSTGRES_PASSWORD=movim \
-v /var/volumes/postgres/:/var/lib/postgresql/data \
-e POSTGRES_DB=movim --net my-net postgres

-> create pgADmin container  to acces to the databse using http
docker create --restart=always --name pgAdmin -p 8000:80 \
 -e "PGADMIN_DEFAULT_EMAIL=macha.jumelin@cohorte-technologies.com" \
-e "PGADMIN_DEFAULT_PASSWORD=postgres" \
--net my-net \
 dpage/pgadmin4

->create xmpp openfire container
docker create --name xmpp  --restart=always \
 -p 9090:9090 -p 5222:5222 -p 7777:7777 \
 -v /var/volumes/openfire/:/var/lib/openfire/ \
 --net my-net gizmotronic/openfire

->create movim container
docker create --name movim --net my-net --restart=always \
-e POSTGRES_DB=movim -e POSTGRES_HOST=postgres \
-e POSTGRES_PORT=5432 -e POSTGRES_USER=root \
-e POSTGRES_PASSWORD=movim -e MOVIM_ADMIN=movim \
-e MOVIM_PASSWORD=movim -e MOVIM_DOMAIN=http://localhost/ \
-p 8080:8080 -e MOVIM_PORT=8080 -e MOVIM_INTERFACE=0.0.0.0 \
movim/movim:0.14.1rc4_

after running all these container

i'm able to connect to my postgres database movim , my xmpp server openfire. But i can't connect to any administrative web interface for movim in order to set the xmpp server to use as well as i can't connect to movim using the Mac OS client . 

**For the movim container**
**Do you have any documentation about how to create a movim container properly ? 
is there any missing environment variable in my docker create container ? 
How to define in the movim container the link to the xmpp container ? 
Is there any web technical interface to configure it using the browser ?** 

Thanks in advance for you quick answer 

Cohorte technologies.

**Comment by kawaii** [comment]
Good morning!

You don't seem to have any kind of reverse proxy (nginx or Apache) container used to serve the Movim application. The Movim container requires a FastCGI compatiable webserver to act as a proxy, it also needs to be able to see the static content (bind mount works). See the following example;
```
services:
  movim:
    image: movim/movim:latest
    volumes:
    - ${PWD}/movim:/var/www/html:rw
  nginx:
    image: nginx:mainline-alpine
    ports:
    - published: 80
      target: 80
    volumes:
    - ${PWD}/nginx:/etc/nginx/conf.d:ro
    - ${PWD}/movim:/var/www/html:ro
version: '3.7'
```
I've removed any `environment` keys from the YAML to keep it simple. You need an nginx container which you can mount configuration into, [here is example nginx configuration](https://hastebin.com/ucazuqotow.php) to use.
