### ISSUE TITLE
Docker container listening on 127.0.0.1:8080

### ISSUE THREAD

**Issue by paulb-opusvl** [movim/movim_docker#40]
Upgrading from 0.21rc2 to 0.21.1 results in movim listening on 127.0.0.1:8080 and not 0.0.0.0:8080. This causes the web application to be unable to connect to the movim server. 

When issuing a netstat command within the movim container, I see it is only listening on localhost, meaning the nginx container cannot connect to port 8080. Nothing in the environment settings has changed other than the version number.

Seems to be ignoring the `MOVIM_INTERFACE` setting.

__Snippet docker-compose.yml__
```
version: '3.7'
services:
  movim:
    depends_on:
      nginx:
        condition: service_started
      prosody:
        condition: service_started
    environment:
      MOVIM_ADMIN: admin
      MOVIM_DOMAIN: https://chat.domain.tld
      MOVIM_INTERFACE: 0.0.0.0
      MOVIM_PASSWORD: SecretKey
      MOVIM_PORT: "8080"
      POSTGRES_DB: movim
      POSTGRES_HOST: postgresql
      POSTGRES_PASSWORD: SecretKey
      POSTGRES_PORT: "5432"
      POSTGRES_USER: movim
    image: movim/movim:0.21.1
    networks:
      default: null
    ports:
    - mode: ingress
      host_ip: 127.0.0.1
      target: 8080
      published: "37012"
      protocol: tcp
    restart: on-failure
    volumes:
    - type: bind
      source: /srv/container-volumes/movim
      target: /var/www/html
      bind:
        create_host_path: true
  nginx:
    image: nginx:mainline-alpine
    networks:
      default: null
    ports:
    - mode: ingress
      host_ip: 127.0.0.1
      target: 80
      published: "37011"
      protocol: tcp
    restart: on-failure
    volumes:
    - type: bind
      source: /srv/container-volumes/movim
      target: /var/www/html
      read_only: true
      bind:
        create_host_path: true
    - type: bind
      source: /srv/container-deployments/movim/deploy/nginx
      target: /etc/nginx/conf.d
      read_only: true
      bind:
        create_host_path: true
```

v0.21rc2
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN
```

v0.21.1
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN
```
